#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'

##########################################
# injects lwc local testing path into
# it/testing.conf
#
configure_lwc_local() {
  echo "lwc_local=\"{\\\"mimirDataDir\\\": \\\"/tmp/lwc-local/\\\"}\"" >> $CONFIGFILE
  echo "lwc_local_insert=\"{}\"" >> $CONFIGFILE
}


##########################################
# injects mimir path into
# it/testing.conf
#
configure_mimir() {
  echo "mimir=\"/tmp/precog/\"" >> $CONFIGFILE
}

##########################################
# injects metastore conf into
# it/testing.conf
#
configure_metastore() {
  echo 'postgresql_metastore="{\"host\":\"'$DOCKERIP'\",\"port\":5432,\"database\":\"metastore\",\"userName\":\"postgres\",\"password\":\"\"}"' >> $CONFIGFILE
}

##########################################
# injects various mongodb urls into
# it/testing.conf depending on argument
#
configure_mongo() {
  CONTAINERNAME=$1
  if [[ $CONTAINERNAME == "mongodb_read_only" ]]; then echo "$CONTAINERNAME=\"mongodb://${DOCKERIP}:27020\"" >> $CONFIGFILE; fi
  if [[ $CONTAINERNAME == "mongodb_3_2"       ]]; then echo "$CONTAINERNAME=\"mongodb://${DOCKERIP}:27021\"" >> $CONFIGFILE; fi
  if [[ $CONTAINERNAME == "mongodb_3_4"       ]]; then echo "$CONTAINERNAME=\"mongodb://${DOCKERIP}:27022\"" >> $CONFIGFILE; fi
  if [[ $CONTAINERNAME == "mongodb_3_4_13"    ]]; then echo "$CONTAINERNAME=\"mongodb://${DOCKERIP}:27023\"" >> $CONFIGFILE; fi
  if [[ $CONTAINERNAME == "mongodb_3_6"       ]]; then echo "$CONTAINERNAME=\"mongodb://${DOCKERIP}:27024\"" >> $CONFIGFILE; fi
}


container_lookup() {
  CONTAINER=$(echo "$1" | cut -d_ -f2-)
  if [[ $CONTAINER =~ "mongodb"        ]]; then configure_mongo          $CONTAINER;      fi
  if [[ $CONTAINER == "metastore"      ]]; then configure_metastore;                      fi
  if [[ $CONTAINER == "mimir"          ]]; then configure_mimir;                          fi
  if [[ $CONTAINER == "lwc_local"      ]]; then configure_lwc_local;                      fi
}


define_needed_evn_vars() {
  if [[ ${TRAVIS:-} ]]
  then
    CONFIGFILE=$TRAVIS_BUILD_DIR/it/testing.conf
    DOCKERIP="localhost"
  elif [[ "$(command -v docker-machine)" && "$(docker-machine ls | grep default)" ]]
  then
    CONFIGFILE=$(dirname $0)/../../it/testing.conf
    eval "$(docker-machine env --shell sh/bash default)"
    DOCKERIP=$(docker-machine ip default)
  else
    CONFIGFILE=$(dirname $0)/../../it/testing.conf
    DOCKERIP="localhost"
  fi
}

cleanup_testing_conf_file() {
  rm -f $CONFIGFILE
}

usage() {
cat << EOF
Usage: $0 [-h] [-a] [-c CONTAINER-NAME]
Assembles Quasar integration configuration file, it/testing.conf, from currently running
continers. Works for local development and within travis-ci.

  -h                   help (also trigged with no parameters): display this help and exit
  -a                   cleans existing testing.conf and adds testing.conf entries for all currently running quasar test containers
  -i CONTAINER-NAME    add CONTAINER-NAME entry to existing testing.conf file
  -c CONTAINER-NAME    cleans exisitng testing.conf and adds a entry for CONTAINER-NAME
EOF
}

# if no args are passed in print usage
[ $# -eq 0 ] && usage

# initialize our env
define_needed_evn_vars

# command line parsing logic
while getopts ":hastpc:i:" opt; do
  case $opt in
    a)
      echo "cleaning existing testing.conf and adding testing.conf entries for all currently running quasar test containers..." >&2
      cleanup_testing_conf_file
      CONTAINERS=$(docker ps --filter "name=" | awk '{if(NR>1) print $NF}' | grep "quasar_")
      for CONTAINER in $CONTAINERS
      do
        container_lookup $CONTAINER
      done
      ;;
    i)
      echo "adding $OPTARG entry to existing testing.conf file..." >&2
      container_lookup $OPTARG
      ;;
    c)
      echo "cleaning exisitng testing.conf and adding a entry for $OPTARG..." >&2
      cleanup_testing_conf_file
      container_lookup $OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
    h | *)
      usage
      exit 1
      ;;
  esac
done
