#!/usr/bin/env bash
set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

MLHOSTNAME=$1
ADMIN_PORT=$2
MANAGE_PORT=$3
URILEX_DISABLED=$4
ML_ADMIN_PREFIX="http://${MLHOSTNAME}:${ADMIN_PORT}/admin/v1"
ML_MANAGE_PREFIX="http://${MLHOSTNAME}:${MANAGE_PORT}/manage/v2"
ML_USERNAME="marklogic"
ML_PASSWORD="marklogic"

await_restart() {
  sleep 20
}

# Initialize the server with the license info
curl -d "" ${ML_ADMIN_PREFIX}/init

# Allow the server to restart
await_restart

# Add the admin user
curl -d "admin-username=${ML_USERNAME}&admin-password=${ML_PASSWORD}" ${ML_ADMIN_PREFIX}/instance-admin

await_restart

# Limit group memory usage
curl -X PUT --anyauth -u "${ML_USERNAME}:${ML_PASSWORD}" -H "Content-Type: application/json" \
  -d '{"list-cache-size": 64, "compressed-tree-cache-size": 64, "expanded-tree-cache-size": 128, "triple-cache-size": 64, "triple-value-cache-size": 64}' \
  ${ML_MANAGE_PREFIX}/groups/Default/properties

await_restart

# Limit database memory usage
curl -X PUT --anyauth -u "${ML_USERNAME}:${ML_PASSWORD}" -H "Content-Type: application/json" \
  -d '{"in-memory-list-size": 64, "in-memory-tree-size": 64}' \
  ${ML_MANAGE_PREFIX}/databases/Documents/properties

# Disable the URI lexicon, if requested.
if [[ "${URILEX_DISABLED:-enabled}" == "disabled" ]]; then
  curl -X PUT --anyauth -u "${ML_USERNAME}:${ML_PASSWORD}" -H "Content-Type: application/json" \
    -d '{"uri-lexicon" : false}' \
    ${ML_MANAGE_PREFIX}/databases/Documents/properties
fi
