#!/usr/bin/env bash
set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

function downloadMLRPM() {
  if [[ $1 =~ "marklogic" ]]
  then
    docker/Dockerfiles/Marklogic/getMLRpm
  fi
}

function upContainer() {
  docker-compose -f docker/docker-compose.yml up -d $1
}

CONTAINER=$1
if [[ $CONTAINER == "quasar_spark_local_test" ]]
then
  echo "$CONTAINER: not starting a container for spark_local_test..."
elif [[ $CONTAINER == "quasar_mimir" ]]
then
  echo "$CONTAINER: not starting a container for mimir..."
elif [[ $CONTAINER =~ "marklogic" ]]
then
  downloadMLRPM $CONTAINER
  upContainer $CONTAINER
  sleep 5
elif ([[ $CONTAINER == "quasar_spark_cassandra" ]] || [[ $CONTAINER == "quasar_spark_hdfs" ]] || [[ $CONTAINER == "quasar_spark_ftp" ]] || [[ $CONTAINER == "quasar_spark_elasticsearch" ]])
then
  upContainer quasar_spark_cluster
  upContainer $CONTAINER
  sleep 5
elif [[ $CONTAINER == "quasar_spark_s3" ]]
then
  upContainer quasar_spark_cluster
  sleep 5
else
  upContainer $CONTAINER
  sleep 5
fi
