package quasar.project

object Versions {
  val algebraVersion      = "1.0.1"
  val argonautVersion     = "6.2.3"
  val catsVersion         = "1.6.0"
  val catsEffectVersion   = "1.3.1"
  val disciplineVersion   = "0.11.1"
  val jawnVersion         = "0.14.2"
  val jawnfs2Version      = "0.14.2"
  val matryoshkaVersion   = "0.18.3"
  val monocleVersion      = "1.5.0"
  val pathyVersion        = "0.2.13"
  val refinedVersion      = "0.9.7"
  val scodecBitsVersion   = "1.1.2"
  val scalacheckVersion   = "1.14.0"
  val scalazVersion       = "7.2.27"
  val scoptVersion        = "3.7.1"
  val shapelessVersion    = "2.3.3"
  val simulacrumVersion   = "0.16.0"
  val specsVersion        = "4.5.1"
  val spireVersion        = "0.16.1"
  val akkaVersion         = "2.5.1"
  val fs2Version          = "1.0.4"
  val slf4sVersion        = "1.7.25"
  val atomixVersion       = "3.0.11"
}
