package quasar.project

object Versions {
  val algebraVersion      = "2.0.0"
  val argonautVersion     = "6.2.3"
  val catsVersion         = "2.0.0"
  val catsEffectVersion   = "2.0.0"
  val disciplineVersion   = "0.11.1"
  val jawnVersion         = "0.14.2"
  val jawnfs2Version      = "0.14.2"
  val matryoshkaVersion   = "0.18.3"
  val monocleVersion      = "1.6.0"
  val pathyVersion        = "0.2.13"
  val refinedVersion      = "0.9.10"
  val scodecBitsVersion   = "1.1.12"
  val scalacheckVersion   = "1.14.3"
  val scalazVersion       = "7.2.30"
  val scoptVersion        = "3.7.1"
  val shapelessVersion    = "2.3.3"
  val simulacrumVersion   = "0.19.0"
  val specsVersion        = "4.8.2"
  val spireVersion        = "0.16.2"
  val akkaVersion         = "2.5.1"
  val fs2Version          = "1.0.5"
  val fs2JobVersion       = "0.0.7"
  val slf4sVersion        = "1.7.25"
  val atomixVersion       = "3.0.11" // This is freezed, because atomix changed discovery service somehow
  val mapdbVersion        = "3.0.7"
  val nettyVersion        = "4.1.44.Final"
}
