package quasar.project

object Versions {
  val algebraVersion      = "2.0.0"
  val argonautVersion     = "6.3.0-M2"
  val catsVersion         = "2.1.0"
  val catsEffectVersion   = "2.1.0"
  val disciplineVersion   = "0.11.1"
  val jawnVersion         = "1.0.0"
  val jawnfs2Version      = "1.0.0-RC2"
  val log4CatsVersion     = "1.0.1"
  val matryoshkaVersion   = "0.18.6"
  val monocleVersion      = "1.6.0"
  val pathyVersion        = "0.3.2"
  val scodecBitsVersion   = "1.1.12"
  val scalacheckVersion   = "1.14.3"
  val scalazVersion       = "7.2.30"
  val scoptVersion        = "3.7.1"
  val shapelessVersion    = "2.3.3"
  val specsVersion        = "4.8.3"
  val spireVersion        = "0.16.2"
  val akkaVersion         = "2.5.1"
  val fs2Version          = "2.3.0"
  val slf4sVersion        = "1.7.25"
  val atomixVersion       = "3.0.11" // This is freezed, because atomix changed discovery service somehow
  val mapdbVersion        = "3.0.8"
  val skolemsVersion      = "0.2.1"
  val kittensVersion      = "2.0.0"
  val iotaVersion         = "0.3.10"
  val drosteVersion       = "0.8.0"
  val h2Version           = "1.4.200"
  val http4sVersion       = "0.21.2"
}
