#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

source "$(dirname $0)/constants"

# Only run for the first travis job
if [[ $CONNECTOR == "mongodb_2_6" ]]; then
  "$SCRIPT_DIR/publishJarIfMaster"
if [[ $CONNECTOR == "mongodb_3_0" ]]; then
  # Upload coverage information to codecov.io (BETA)
  pip install --user codecov && codecov
fi
