#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

#
# This script is intended to be run by continuous integration tools, allowing
# actual details of the build and test process to change without having to
# update CI configuration.
#

echo "running build script..."

source "$(dirname $0)/constants"

# FIXME: Remove travis_wait usages when associated phases produce output
#        more frequently than Travis's 10 minute imposed window
TRAVIS_MAX_CONNECTOR_COMPILE_MINS=40
TRAVIS_MAX_DOC_MINS=20

# if we're building a pull request, DON'T clean and use the cache instead
if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
  CLEAN=clean
  COVERAGE=coverage
  COVERAGE_REPORT=coverageReport
else
  CLEAN=
  COVERAGE=
  COVERAGE_REPORT=
fi

# only do code coverage on job .1 AND on a non-pull request
if [[ $CONNECTOR == "mongodb_2_6" ]]; then
  # Compiling `connector` can take awhile, so allow it some extra time when
  # running on travis to avoid having the build killed due to lack of output.
  echo "Compiling connector — could take up to $TRAVIS_MAX_CONNECTOR_COMPILE_MINS minutes"
  if [[ ${TRAVIS:-} ]]; then
    travis_wait $TRAVIS_MAX_CONNECTOR_COMPILE_MINS "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION $CLEAN connector/test:compile
  else
    "$SBT" ++$TRAVIS_SCALA_VERSION $CLEAN
  fi

  # Require that all header comments are present before proceeding, then
  # build and run all tests everywhere (including integration)
  "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION checkHeaders test exclusive:test

  # In a fresh JVM process, re-compile without coverage in order to get a jar
  # that does not contain instrumentation.
  "$SBT" ++$TRAVIS_SCALA_VERSION 'web/assembly'

  # Running `doc` can take awhile, so allow it some extra time when
  # running on travis to avoid having the build killed due to lack of output.
  if [[ ${TRAVIS:-} ]]; then
    travis_wait $TRAVIS_MAX_DOC_MINS "$SBT" ++$TRAVIS_SCALA_VERSION doc
  else
    "$SBT" ++$TRAVIS_SCALA_VERSION doc
  fi

  # Test to ensure the JAR file is valid:
  "$SCRIPT_DIR/testJar"
  TEST_STATUS=$?

  echo "Result of Quasar JAR test: $TEST_STATUS"

  exit $TEST_STATUS
elif [[ $CONNECTOR == "mongodb_3_0" ]]; then
  echo "Compiling connector — could take up to $TRAVIS_MAX_CONNECTOR_COMPILE_MINS minutes"
  if [[ ${TRAVIS:-} ]]; then
    travis_wait $TRAVIS_MAX_CONNECTOR_COMPILE_MINS "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION $CLEAN $COVERAGE connector/test:compile
  else
    "$SBT" ++$TRAVIS_SCALA_VERSION $CLEAN
  fi

  # Require that all header comments are present before proceeding, then
  # build and run all tests everywhere (including integration)
  "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION checkHeaders $COVERAGE test exclusive:test $COVERAGE_REPORT
else
  # Compiling `connector` can take awhile, so allow it some extra time when
  # running on travis to avoid having the build killed due to lack of output.
  echo "Compiling connector — could take up to $TRAVIS_MAX_CONNECTOR_COMPILE_MINS minutes"
  if [[ ${TRAVIS:-} ]]; then
    travis_wait $TRAVIS_MAX_CONNECTOR_COMPILE_MINS "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION $CLEAN connector/test:compile
  fi

  # Not the first job in Travis; run only integration tests (no sense
  # re-doing work that isn't affected by the available backends)
  "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION it/test it/exclusive:test
fi
