#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

#
# This script is intended to be run by continuous integration tools, allowing
# actual details of the build and test process to change without having to
# update CI configuration.
#

echo "running build2..."

source "$(dirname $0)/constants"

TRAVIS_MAX_CONNECTOR_COMPILE_MINS=40
JOB_NUM=${TRAVIS_JOB_NUMBER:="1"}



# only do code coverage on job .1 AND on a non-pull request
if [[ "${JOB_NUM##*.}" == "1" ]]; then
  # Compiling `connector` can take awhile, so allow it some extra time when
  # running on travis to avoid having the build killed due to lack of output.
  echo "in job #1 building connector, this will take a while..."
  if [[ ${TRAVIS:-} ]]; then
    travis_wait $TRAVIS_MAX_CONNECTOR_COMPILE_MINS "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION clean coverage connector/test:compile
  else
    "$SBT" ++$TRAVIS_SCALA_VERSION clean
  fi

  # Require that all header comments are present before proceeding, then
  # build and run all tests everywhere (including integration)
  "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION checkHeaders coverage test exclusive:test coverageReport

  # In a fresh JVM process, re-compile without coverage in order to get a jar
  # that does not contain instrumentation. Generate doc.
  "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION clean 'web/assembly' doc

  # Test to ensure the JAR file is valid:
  "$SCRIPT_DIR/testJar"
  TEST_STATUS=$?

  echo "Result of Quasar JAR test: $TEST_STATUS"

  exit $TEST_STATUS
else
  # Compiling `connector` can take awhile, so allow it some extra time when
  # running on travis to avoid having the build killed due to lack of output.
  echo "in job > #1 building connector, this will take a while..."
  if [[ ${TRAVIS:-} ]]; then
    travis_wait $TRAVIS_MAX_CONNECTOR_COMPILE_MINS "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION clean connector/test:compile
  fi

  # Not the first job in Travis; run only integration tests (no sense
  # re-doing work that isn't affected by the available backends)
  "$SBT" -DisIsolatedEnv=${ISOLATED_ENV:=false} ++$TRAVIS_SCALA_VERSION it/test it/exclusive:test
fi
