#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

WS_DIR="$SCRIPT_DIR/.."

SBT="$WS_DIR/sbt"

TEMP_DIR="$WS_DIR/tmp"

mkdir -p "$TEMP_DIR"

# quasar version, from build.sbt:
QUASAR_VERSION=$(cat $WS_DIR/version.sbt | sed -n -e 's/^ *version.*:= "\(.*\)"[^\n]*/\1/p')

QUASAR_WEB_JAR="quasar-web-assembly-${QUASAR_VERSION}.jar"
QUASAR_WEB_JAR_DIR="$WS_DIR/.targets/web/scala-2.12"
QUASAR_WEB_JAR_PATH="$QUASAR_WEB_JAR_DIR/$QUASAR_WEB_JAR"

echo "Quasar Version: $QUASAR_VERSION"
