#!/usr/bin/env bash
set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

ML_VERSION="8.0-5.8"
ML_DEV_URL="https://developer.marklogic.com"
ML_DEV_LOGIN="${ML_DEV_URL}/login"
ML_DEV_GET_TOKEN="${ML_DEV_URL}/get-download-url"
ML_DEV_COOKIES=".ml-dev-cookies"

ML_ASSET_PATH="/download/binaries/8.0/MarkLogic-RHEL6-${ML_VERSION}.x86_64.rpm"
ML_DOWNLOAD_EMAIL="quasarci@slamdata.com"
ML_DOWNLOAD_PASSWORD="quasarci"

ML_DOCKER_DIR="scripts/marklogic"
ML_IMG_NAME="marklogic:${ML_VERSION}"
ML_CNT_NAME="ml8"

ML_ADMIN_PREFIX="http://localhost:8001/admin/v1"
ML_USERNAME="marklogic"
ML_PASSWORD="marklogic"

# Login to developer.marklogic.com
curl -X POST --data "email=${ML_DOWNLOAD_EMAIL}&password=${ML_DOWNLOAD_PASSWORD}" -c $ML_DEV_COOKIES $ML_DEV_LOGIN

# Obtain a download URL
ML_DOWNLOAD_PATH="$(curl -X POST --data "download=$ML_ASSET_PATH" -b $ML_DEV_COOKIES $ML_DEV_GET_TOKEN | jq -r '.path')"

# Fetch the MarkLogic binary
curl -o $ML_DOCKER_DIR/MarkLogic.rpm "${ML_DEV_URL}${ML_DOWNLOAD_PATH}"

# Build the docker image
docker build --rm=true --tag $ML_IMG_NAME $ML_DOCKER_DIR

# Start the MarkLogic container
docker run -d --name $ML_CNT_NAME -p 8000-8002:8000-8002 $ML_IMG_NAME

# Allow the server to start
sleep 20

# Initialize the server with the license info
curl --anyauth -i -X POST -d "" ${ML_ADMIN_PREFIX}/init

# Allow the server to restart
sleep 20

# Add the admin user
curl -i -X POST --data "admin-username=${ML_USERNAME}&admin-password=${ML_PASSWORD}" ${ML_ADMIN_PREFIX}/instance-admin

# TODO: Add indexes as needed to speedup tests
