#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

# Create a tag/release on github, and upload the already-built JAR.
# Using curl to POST to the github API.

source "$(dirname $0)/constants"

if [[ ! -v GITHUB_TOKEN ]] ; then
    echo "GITHUB_TOKEN not defined, skipping publishing JAR"

    exit 0
fi

# only publish on quasar-analytics/quasar branches master and backport/*
if [[ "$TRAVIS" == "true"                                              &&
      ("$TRAVIS_BRANCH" == "master" || "$TRAVIS_BRANCH" == backport/*) &&
      "$TRAVIS_REPO_SLUG" == "quasar-analytics/quasar" ]] ; then

    # 'set every sparkDependencyProvided := true' \
    # sparkcore/githubRelease \

  "$SBT" \
    repl/githubRelease \
    web/githubRelease \
    couchbase/githubRelease \
    mongodb/githubRelease \
    marklogic/githubRelease
else
  echo "GITHUB_TOKEN defined, but Travis not running in quasar-analytics/quasar branches master or backport/*, so skipping publish"
fi
