#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

source scripts/constants

"$SBT" transferPublishAndTagResources

scripts/publishAndTag 'slamdata/quasar'


bumpInDownstream() { echo $1 > quasar-version; }
export -f bumpInDownstream

# internal
for c in slamdata-backend quasar-repl mimir thoth benchmarks scion; do
  scripts/bumpDependentProject slamdata $c bumpInDownstream
done

# datasources
for c in s3 azure url mongo postgres; do
  scripts/bumpDependentProject slamdata "quasar-datasource-$c" bumpInDownstream
done

# destinations
for c in thoughtspot postgres s3 azure snowflake avalanche redshift; do
  scripts/bumpDependentProject slamdata "quasar-destination-$c" bumpInDownstream
done
