#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

source scripts/constants

"$SBT" transferPublishAndTagResources

# Set TRAVIS_JOB_NUMBER as a workaround to meet sbt-slamdata's publishAndTag assumption
TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar'


bumpInDownstream() { echo $1 > quasar-version; }
export -f bumpInDownstream

# internal
for c in slamdata-backend quasar-repl mimir thoth; do
  scripts/bumpDependentProject slamdata $c bumpInDownstream
done

# datasources
for c in s3 azure url mongo; do
  scripts/bumpDependentProject slamdata "quasar-datasource-$c" bumpInDownstream
done
