#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

source scripts/constants

"$SBT" transferPublishAndTagResources

# Set TRAVIS_JOB_NUMBER as a workaround to meet sbt-slamdata's publishAndTag assumption
TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar'


bumpInSlamdataBackend() { echo $1 > quasar-version; }
export -f bumpInSlamdataBackend
scripts/bumpDependentProject slamdata slamdata-backend bumpInSlamdataBackend
