#!/usr/bin/env bash
set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

set -x

docker run -d --name cb -p 8091-8094:8091-8094 -p 11210:11210 couchbase/server:enterprise-4.5.1

sleep 10

# init

CB='http://Administrator:password@0.0.0.0'

curl -v $CB:8091/node/controller/setupServices -d services=kv%2Cn1ql%2Cindex%2Cfts

curl -v $CB:8091/settings/web -d port=8091 -d username=Administrator -d password=password

curl -v -X POST $CB:8091/settings/indexes -d 'storageMode=memory_optimized'

sleep 5

curl -v -X POST $CB:8091/pools/default -d memoryQuota=400 -d indexMemoryQuota=1024

sleep 5

curl -v -X POST $CB:8091/pools/default/buckets -d 'ramQuotaMB=100&name=default&authType=sasl'

sleep 5

curl -v -X POST $CB:8091/pools/default/buckets -d 'ramQuotaMB=100&name=quasar-test&authType=sasl'

sleep 5

curl -v -X POST $CB:8093/query -d 'statement=create primary index on `quasar-test`'

sleep 5

curl -v -X POST $CB:8093/query -d 'statement=create index quasar_test_type_idx on `quasar-test`(type)'
