#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

source "$(dirname $0)/constants"

# NB: This assumes Linux
CONFIG_DIR=$HOME/.config/quasar
CONFIG_FILE=$CONFIG_DIR/quasar-config.json

if [ ! -e $CONFIG_FILE ]
then
    mkdir -p $CONFIG_DIR
    cp $(dirname $0)/../example-quasar-config.json $CONFIG_FILE
fi

QUASAR_SUCCESS_OUTPUT="(v$QUASAR_VERSION) 💪 $"
QUASAR_LOG_FILE="$TEMP_DIR/quasarout.log"

echo "Initializing Quasar MetaStore..."

java -jar "$QUASAR_REPL_JAR_PATH" initUpdateMetaStore

echo "Launching Quasar REPL JAR..."

java -jar "$QUASAR_REPL_JAR_PATH" &> "$QUASAR_LOG_FILE" &
QUASAR_PID=$!

echo "Quasar PID: $QUASAR_PID"

sleep 10

cat $QUASAR_LOG_FILE

echo "Killing Quasar JAR..."

kill -9 $QUASAR_PID
KILL_STATUS=$?

echo "Status code from killing Quasar: $KILL_STATUS"

if [[ $(cat "$QUASAR_LOG_FILE") == *"$QUASAR_SUCCESS_OUTPUT"* ]]
then
  echo "Quasar successfully started"

  exit 0
else
  >&2 echo "Quasar failed to start"

  exit 1
fi
