#!/usr/bin/env bash

set -euo pipefail # STRICT MODE
IFS=$'\n\t'       # http://redsymbol.net/articles/unofficial-bash-strict-mode/

source "$(dirname $0)/constants"

QUASAR_SUCCESS_OUTPUT="(v$QUASAR_VERSION) 💪 $"
QUASAR_LOG_FILE="$TEMP_DIR/quasarout.log"

echo "Launching Quasar REPL JAR..."

# This should launch the repl but opposed to the aeshell based repl
# the jline3 based one also terminates immediately after launching
# with an org.jline.reader.EndOfFileException
# As a consequence later in this script the process won't typically be there
# when we try to kill it. Still we attempt to kill it, if for some reason the
# process is still there.
java -jar "$QUASAR_REPL_JAR_PATH" &> "$QUASAR_LOG_FILE" &
QUASAR_PID=$!

echo "Quasar PID: $QUASAR_PID"

sleep 20

cat $QUASAR_LOG_FILE

echo "Killing Quasar JAR if necessary..."

set +e
kill -9 $QUASAR_PID
set -e
KILL_STATUS=$?

echo "Status code from killing Quasar: $KILL_STATUS"

if [[ $(cat "$QUASAR_LOG_FILE") == *"$QUASAR_SUCCESS_OUTPUT"* ]]
then
  echo "Quasar successfully started"

  exit 0
else
  >&2 echo "Quasar failed to start"

  exit 1
fi
